language: node_js
node_js:
  - '12'

before_script:
  - chmod +x .vuepress/scripts/build.sh

script: .vuepress/scripts/build.sh

# branch whitelist, only for GitHub Pages
branches:
  only:
    - source

cache: npm # caching npm will speed up build

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: .vuepress/dist
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  target_branch: master
  on:
    branch: source
