# This is a basic workflow to help you get started with Actions

name: autobuild

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the source branch
  push:
    branches: [source]
  pull_request:
    branches: [source]
  # schedule:
  # * is a special character in YAML so you have to quote this string
  # run every night:
  # - cron: '44 2 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      logLevel:
        required: true
        description: 'Log level'
        default: 'warning'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 12

      - name: CI Build
        run: |
          bash .vuepress/scripts/build.sh

      - name: CI Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .vuepress/dist
          publish_branch: gh-pages
          force_orphan: true
